version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-nest
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-nest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  postgres-data:
